# Generated by Django 5.1.3 on 2024-12-07 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='created_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='open_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
