# Generated by Django 5.1.3 on 2024-12-08 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_created_by_alter_document_open_id_and_more'),
        ('signers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signer',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='documents.document'),
        ),
    ]
